apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: api-readwriter
rules:
- apiGroups: ["","*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list", "update", "patch"]