apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryvww2566.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  type: ClusterIP
  selector:
    app: tripviewer
  ports:
  - port: 80
    targetPort: 80

