apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryvww2566.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret01
          mountPath: "/secrets"
          readOnly: true
        env:
          - name: SQL_SERVER
            value: sqlservervww2566.database.windows.net
          #- name: SQL_USER
          #  valueFrom:
          #    secretKeyRef:
          #      name: sql-secret
          #      key: sql-user
          #- name: SQL_PASSWORD
          #  valueFrom:
          #    secretKeyRef:
          #      name: sql-secret
          #      key: sql-password

      volumes:
      - name: secret01
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "team06"

---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: trips
  ports:
  - port: 80
    targetPort: 80
