apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  labels:
    deploy: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryvww2566.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile
          - name: TRIPS_API_ENDPOINT
            value: http://trips
          - name: BING_MAPS_KEY
            value: ''

---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  type: LoadBalancer
  selector:
    app: tripviewer
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80

