apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryvww2566.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
        env:
          - name: SQL_SERVER
            value: sqlservervww2566.database.windows.net
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: sql-user
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: sql-password

---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app: user-java
  ports:
  - port: 80
    targetPort: 80
