# This is a SecretProviderClass example using workload identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: team06
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    clientID: "8ab665b5-d7f8-41a0-b379-adfd1e467fb0"
    keyvaultName: kv-challenge4
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: sql-user
          objectAlias: SQL_USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: sql-password
          objectAlias: SQL_PASSWORD
          objectType: secret
          objectVersion: ""
    tenantId: "4e022c53-1904-4678-8747-1e05b8a43c5e"        # The tenant ID of the key vault

#apiVersion: secrets-store.csi.x-k8s.io/v1
#kind: SecretProviderClass
#metadata:
#  name: team06
#spec:
#  provider: azure
#  secretObjects:
#  - data:
#    - key: sql-user
#      objectName: foo1
#    - key: sql-password
#      objectName: foo2
#    secretName: sql
#    type: Opaque
